# (c) Copyright 2021 Christian Saide
# SPDX-License-Identifier: MIT

name: publish

on:
  push:
    tags: [ "v*" ]

env:
  CARGO_TERM_COLOR: always
  RUST_TOOLCHAIN: stable
  TOOLCHAIN_PROFILE: minimal

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: ${{ env.TOOLCHAIN_PROFILE }}
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          override: true
      - name: Cache
        uses: Swatinem/rust-cache@v1
      - name: Publish
        run: make CARGO_API_KEY="${{secrets.CRATES_RS_TOKEN}}" publish-ci
