name: Rust

on:
  push:
    branches: [ develop, main ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ develop, main ]
    paths-ignore:
      - '**.md'

env:
  CARGO_TERM_COLOR: always
  RUST_TOOLCHAIN: stable
  TOOLCHAIN_PROFILE: minimal

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: ${{ env.TOOLCHAIN_PROFILE }}
        toolchain: ${{ env.RUST_TOOLCHAIN }}
        override: true
        components: rustfmt, clippy
    - name: Cache
      uses: Swatinem/rust-cache@v1
    - name: Build
      run: make compile.linux-amd64
    - name: Run tests
      run: make check
